name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate que esta sea la rama principal de tu repositorio (puede ser 'master')
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # El sistema operativo donde se construirá tu app

    steps:
      - name: Checkout code # Descarga tu código del repositorio
        uses: actions/checkout@v3

      - name: Set up Node.js # Configura Node.js para construir tu React App
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Versión de Node.js, compatible con React 18

      - name: Install dependencies # Instala las librerías de tu proyecto (node_modules)
        run: npm install

      - name: Build React App with Env Variables # ¡Paso CRÍTICO: Construye tu aplicación React!
        run: npm run build # Ejecuta el script 'build' de tu package.json
        env: # <--- ¡AQUÍ LE DECIMOS A LA APP CUÁLES SON LAS CLAVES!
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }} # Clave URL de Supabase
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }} # Clave ANON de Supabase
          # Si usaste claves de Firebase en .env, DESCOMENTA Y AÑADELAS AQUÍ TAMBIÉN.
          # Si no, déjalas comentadas con el #.
          # REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          # REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          # REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          # REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          # REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          # REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}

      - name: Deploy to GitHub Pages # Sube tu aplicación construida a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Una acción popular para gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de seguridad automático de GitHub
          publish_dir: ./build # La carpeta de tu app compilada